#
# Generated by erpcgen 1.9.1 on Thu Sep 15 09:19:22 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for evb_to_pc
class Ievb_to_pc(object):
    SERVICE_ID = 1
    NS_RPC_DATA_SENDBLOCKTOPC_ID = 1
    NS_RPC_DATA_FETCHBLOCKFROMPC_ID = 2
    NS_RPC_DATA_COMPUTEONPC_ID = 3
    NS_RPC_DATA_REMOTEPRINTONPC_ID = 4

    def ns_rpc_data_sendBlockToPC(self, block):
        raise NotImplementedError()

    def ns_rpc_data_fetchBlockFromPC(self, block):
        raise NotImplementedError()

    def ns_rpc_data_computeOnPC(self, in_block, result_block):
        raise NotImplementedError()

    def ns_rpc_data_remotePrintOnPC(self, msg):
        raise NotImplementedError()
