nn_arch:
  - layer_neurons: 257 # input neurons
  - layer_type: unet # layer 0
    dropout: 0.1
    activation: tanh
    is_causal: False
    separable: False
    layer_neurons: 257
    kernel_size_time: 3
    num_chs: [1, 2, 4, 8, 16]
  - layer_type: fc # layer 1
    layer_neurons: 257
    dropout: 0.25
    activation: sigmoid
feat:
  type: 'pspec'
  num_context: 1