# Put your local overrides in here
# EVB    :=blue_evb
# DEFINES+= CFG_TUSB_DEBUG=2
# TF_VERSION := R2.3.1
# AS_VERSION := R4.1.0

# DEFINES+= NS_AUDIO_DMA_BUFFER_SIZE=16000
# DEFINES+= NS_MALLOC_HEAP_SIZE_IN_K=24

