#
# Generated by erpcgen 1.9.1 on Thu Sep 15 09:19:22 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

try:
    from erpc import erpc_version

    version = erpc_version.ERPC_VERSION
except ImportError:
    version = "unknown"
if version != "1.9.1":
    raise ValueError(
        'The generated shim code version (1.9.1) is different to the rest of eRPC code (%s). \
Install newer version by running "python setup.py install" in folder erpc/erpc_python/.'
        % repr(version)
    )

from . import client, common, interface, server
