#
# Generated by erpcgen 1.9.1 on Thu Sep 15 09:19:22 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for pc_to_evb
class Ipc_to_evb(object):
    SERVICE_ID = 2
    NS_RPC_DATA_SENDBLOCKTOEVB_ID = 1
    NS_RPC_DATA_FETCHBLOCKFROMEVB_ID = 2
    NS_RPC_DATA_COMPUTEONEVB_ID = 3

    def ns_rpc_data_sendBlockToEVB(self, block):
        raise NotImplementedError()

    def ns_rpc_data_fetchBlockFromEVB(self, block):
        raise NotImplementedError()

    def ns_rpc_data_computeOnEVB(self, in_block, result_block):
        raise NotImplementedError()
